web:
  image: aintohvri/docker-drubian:6
  working_dir: /var/www/drupal.dev
  volumes:
    - .:/docker
    - ~/.ssh:/home/deploy/.ssh
  ports:
    - "80:80"
  expose:
    - "80"
  links:
    - mysql
mysql:
  image: mysql:5.5
  restart: always
  expose:
    - "3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: drupal6
